version: '3.8'

services:
  app:
    build: .
    container_name: mimic_app
    ports:
      - "3000:3000"
    environment:
      # O host aponta para o nome do serviço 'db'
      - DATABASE_URL=host=db user=postgres password=postgres dbname=mimic_db port=5432 sslmode=disable
      - PORT=3000
      - SECRET_KEY=chave_super_secreta_padrao_para_docker
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: mimic_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mimic_db
    volumes:
      - mimic_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mimic_pgdata:
